### ISSUE TITLE
Search Highlighting

### ISSUE THREAD

**Issue by ruchi-shekar** [Magana/roadtripr#55] opened 2018-04-11 18:40 UTC
We would like to see the search word highlighted in the search results.

**Comment by AmruthaSreedharane** [comment] 2018-04-11 18:48
<img width="1191" alt="screen shot 2018-04-11 at 1 48 12 pm" src="https://user-images.githubusercontent.com/14795011/38636870-12392434-3d8f-11e8-9600-c7e576ba63dc.png">

**Comment by Magana** [comment] 2018-04-11 19:07
Duplicate of #36

**Closed** 2018-04-18 20:03 UTC
Labels: bug, user stories
